### ISSUE TITLE
Can't validate regex pattern of field.

### ISSUE THREAD

**Issue by saadat-atta-brainx** [nerdgeschoss/muffin#10]
Hi, i want to validate field using regex. I am adding code to my form class.
`validates :name, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" }`
But it only shows required:true in generated html. No pattern attribute is present. 
Does this gem only validates required type?
Thanks

**Comment by JensRavens** [comment]
Muffin does not generate any html for you - it's just a model object. As a convenience it also offers a list of `required_attributes`, but that's it. 

If you want to implement anything like this, you could take some inspiration from how the `required` attribute is retrieved - just look for format validators instead of presence validators:

https://github.com/nerdgeschoss/muffin/blob/5c055d5a668506ab41a869e5ca9d6031d32dc2cb/lib/muffin/frostings/validation.rb#L22-L27

**Comment by saadat-atta-brainx** [comment]
ok. Thanks for clarifying.
